name: Daily Tests

on:
  schedule:
    # Run at 2:00 UTC every day
    - cron: '0 2 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            libssl-dev \
            libopus-dev \
            ffmpeg \
            python3
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Run tests
        run: cargo test --all
      
      - name: Send notification on failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Daily Tests Failed"
          description: "Daily tests for cracktunes failed. Check the logs for details."
          color: 0xFF0000
          username: "GitHub Actions"
