name: Pull Request

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            libssl-dev \
            libopus-dev \
            ffmpeg \
            python3
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0
          components: clippy, rustfmt
      
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy -- -D warnings
      
      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --all
      
      - name: Build Docker image
        run: docker build -t cracktunes:pr-${{ github.event.pull_request.number }} .
      
      - name: Send success notification
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "PR #${{ github.event.pull_request.number }} Checks Passed"
          description: "All checks have passed for PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          color: 0x00FF00
          username: "GitHub Actions"
      
      - name: Send failure notification
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "PR #${{ github.event.pull_request.number }} Checks Failed"
          description: "Some checks have failed for PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}. Please check the logs for details."
          color: 0xFF0000
          username: "GitHub Actions"
